# Generated by Django 5.0 on 2023-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('guessed_letters', models.CharField(default='', max_length=50)),
                ('incorrect_guesses', models.PositiveIntegerField(default=0)),
                ('max_incorrect_guesses', models.PositiveIntegerField(default=0)),
                ('game_state', models.CharField(default='InProgress', max_length=20)),
            ],
        ),
    ]
